name: Convert LaTeX to HTML

on:
  push:
    branches:
      - main    # Watch the main branch for changes

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install pandoc
        run: sudo apt-get install -y pandoc

      - name: Convert LaTeX to HTML
        run: pandoc Outline.tex -o outline.html

      - name: Commit and push changes
        env:
          TOKEN: ${{ secrets.ACTIONS_SECRET_GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add outline.html
          git commit -m 'Convert LaTeX to HTML'
          git push https://x-access-token:${TOKEN}@github.com/tomoto0/Outline.git
