name: Convert TeX to HTML

on:
  push:
    paths:
      - '**.tex'

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install pandoc
      run: sudo apt-get install pandoc
    
    - name: Convert TeX to HTML
      run: |
        for file in *.tex
        do
          pandoc "$file" -o "${file%.tex}.html"
        done
    
    - name: Commit HTML files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *.html
        git commit -m "Convert TeX to HTML" || echo "No changes to commit"
        git push
