name: Build LaTeX document

on:
  push:
    branches:
      - main  # or the branch you are working on

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Latest version as of writing

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: Outline.tex  # Replace with your main TeX file
        latexmk_shell_escape: true  # Set to true if needed

    - name: Upload PDF
      uses: actions/upload-artifact@v3  # Latest version as of writing
      with:
        name: pdf
        path: outline.pdf  # Replace with the path to your generated PDF file

