name: Sync with tomoto0.github.io

on:
  push:
    branches:
      - main

jobs:
  synchronize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout primary repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add secondary repository as remote
        env:
          ACTIONS_SECRET_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote add secondary https://tomoto0:${{ secrets.ACTIONS_SECRET_GITHUB_TOKEN }}@github.com/tomoto0/tomoto0.github.io.git

      - name: Push to secondary repository
        run: |
          git push secondary main
